### ISSUE TITLE
SSL cert issue

### ISSUE THREAD

**Issue by aram535** [datumbox/ansible-jprofiler#1]
Hi, 

I'm getting the following error: 

> MSG:
> 
> Failed to validate the SSL certificate for download-keycdn.ej-technologies.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 8] _ssl.c:492: EOF occurred in violation of protocol.

which is an SSL error at the CDN, so I tried adding 

`validate_certs: no`

to the get_url section.  That resulted in:

> fatal: [ap-uat]: FAILED! => {
>     "changed": false, 
>     "dest": "/tmp/jprofiler_linux_10_0_4.sh", 
>     "failed": true, 
>     "state": "absent", 
>     "url": "https://download-keycdn.ej-technologies.com/jprofiler/jprofiler_linux_10_0_4.sh"
> }
> 
> MSG:
> 
> Request failed: <urlopen error [Errno 8] _ssl.c:492: EOF occurred in violation of protocol>

I did run a yum update & pip list --outdated on my machine and everything relevant is up to date.

**Comment by datumbox** [comment]
Hi @aram535,

Even though I'm quite new to ansible, I think that this is not a problem of the plugin but rather related to your python version (again I don't claim any expertese on the topic).

Have you seen this old Ansible issue? https://github.com/ansible/ansible/issues/12161

**Comment by aram535** [comment]
Quite possibly -- that's why I made sure I did the update.  I'll check the link though ... thanks.
